name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.SSH_PATH }}
            git pull https://Cottonnion:${{ secrets.GH_TOKEN }}@github.com/Cottonnion/gohighlevel-integration-plugin.git ${{ github.ref_name }}
            composer install --no-dev --optimize-autoloader --no-interaction
